### ISSUE TITLE
Folder is created instead of file and file has wrong name

### ISSUE THREAD

**Issue by FreePhoenix888** [CEHR2005/deep-export#12]
Here is the option I passed: 
```
--file "deep.json" 
```
Result:
![image](https://github.com/CEHR2005/deep-export/assets/66206278/93b3a681-fc1c-4091-8936-da3a1d025491)
![image](https://github.com/CEHR2005/deep-export/assets/66206278/3736258a-19ed-484e-b91a-2c778fc9b4fc)

**Comment by CEHR2005** [comment]
This is done because, in addition to the links stored in json, the files associated with them will also be saved. Currently png jpg and other images, in the future the list may expand. When saving, you don't need to specify the file extension, just whatever you want to name the save.
